# Generated by Django 5.0.3 on 2024-04-03 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_conference_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='review',
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.FileField(upload_to='research_papers/')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
            ],
        ),
    ]
