# Generated by Django 5.0.3 on 2024-04-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_remove_conference_review_researchpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='research_paper',
            field=models.FileField(blank=True, null=True, upload_to='research_papers/'),
        ),
        migrations.DeleteModel(
            name='ResearchPaper',
        ),
    ]
